export default {
	durationPrompt: 'How long do you want to meditate?',
	minutesShort: 'min',
	timeMeditated: 'Time meditated',
	streak: 'Streak',
	longestStreak: 'Longest streak',
	beginMeditation: 'Begin meditation',
	pickDuration: 'Pick duration for your meditation',
	picked: 'Picked:',
	cancel: 'Cancel',
	submit: 'Submit',
	areYouSure: 'Are you sure',
	areYouSureDescription: 'Do you really want to leave current meditation?',
	stay: 'Stay',
	leave: 'Leave',
}